name: equational-reasoning-induction
version: '0.6.0.0'
synopsis: Proof assistant for Haskell using DataKinds & PolyKinds
description: ! 'A simple convenient library to write equational / preorder proof as in Agda.
                     This package depends on @singletons@ and generates induction schemes.'
category: Math
author: Hiromi ISHII
maintainer: konn.jinro_at_gmail.com
copyright: (c) Hiromi ISHII 2013-2018
license: BSD3
git: git://github.com/konn/equational-reasoning-induction.git
tested-with: GHC==8.0.2 GHC==8.2.2 GHC==8.4.1 GHC==8.6.3
dependencies:
- base >=4 && <5
- template-haskell >=2.11 && <2.16
- th-extras ==0.0.*
- singletons
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Proof.Induction
  when:
  - condition: impl(ghc <8.4)
    dependencies:
    - semigroups ==0.18.*
